apiVersion: v1
kind: Service

metadata:
  name: {{ include "shopsphere.fullname" . }}-frontend
  labels:
    app: frontend

spec:
  type: {{ .Values.frontend.service.type }}

  selector:
    app: frontend

  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
