apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ include "shopsphere.fullname" . }}-postgres-pvc

spec:
  storageClassName: ebs-sc

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
