apiVersion: v1
kind: Secret

metadata:
  name: {{ include "shopsphere.fullname" . }}-secret

type: Opaque

stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
