apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "shopsphere.fullname" . }}-user-service
  labels:
    app: user-service

spec:
  replicas: {{ .Values.userService.replicaCount }}

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service

          image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"

          imagePullPolicy: {{ .Values.userService.image.pullPolicy }}

          ports:
            - containerPort: 8000
              protocol: TCP

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "shopsphere.fullname" . }}-config
                  key: DB_HOST

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "shopsphere.fullname" . }}-config
                  key: DB_PORT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "shopsphere.fullname" . }}-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "shopsphere.fullname" . }}-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "shopsphere.fullname" . }}-secret
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
