apiVersion: v1
kind: Service

metadata:
  name: {{ include "shopsphere.fullname" . }}-user-service
  labels:
    app: user-service

spec:
  type: {{ .Values.userService.service.type }}

  selector:
    app: user-service

  ports:
    - protocol: TCP
      port: {{ .Values.userService.service.port }}
      targetPort: {{ .Values.userService.service.targetPort }}
